# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rjVcXM1k4pp4x7f7DJHgeos9tVZ8ZRRj
"""

p=int(input("enter principle amt:"))
t=int(input("enter time:"))
r=int(input("enter rate:"))
si=(p*t*r)/100
print("simple interest is:",si)

